---
test:
  clients:
    type: local
    number: 5

  rounds:
  - label: initLedger
    txNumber:
    - 1             
    rateControl:
    - type: fixed-rate
      opts:
        tps: 1
    callback: ../inventory/blockchain/benchmark/electronic-health-record/initLedger.js

  - label: common
    txDuration:
    - 180
    rateControl:
    - type: fixed-rate
      opts:
        tps: 100
    callback: ../inventory/blockchain/benchmark/electronic-health-record/common.js

  - label: readBlockchain
    txNumber:
    - 1
    rateControl:
    - type: fixed-rate
      opts:
        tps: 1
    callback: ../inventory/blockchain/benchmark/electronic-health-record/doNothing.js

monitor:
  type:
  - process
  process:
  - command: node
    arguments: local-client.js
    multiOutput: avg
  interval: 1
