apiVersion: v1
kind: PersistentVolume
metadata:
  name: mosquittopv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /opt/share/caliper/mosquitto
    server: 172.24.55.138

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 namespace: default
 name: mosquittopv
spec:
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 10Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose -f caliper-compose.yaml convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: mosquitto
  name: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mosquitto
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose -f caliper-compose.yaml convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: mosquitto
    spec:
      containers:
        - image: eclipse-mosquitto
          name: mosquitto
          volumeMounts:
          - mountPath: /mosquitto/config
            name: conf-volume
          ports:
            - containerPort: 1883
            - containerPort: 9001
          resources: {}
      hostname: mosquitto
      restartPolicy: Always
      volumes:
      - name: conf-volume
        persistentVolumeClaim:
              claimName: mosquittopv
status: {}
