test:
  workers:
    type: local
    number: 5
  rounds:
    - label: Init Ledger.
      txNumber: 1
      rateControl:
        type: fixed-rate
        opts: 
          tps: 1
      workload:
        arguments:
          assets: 10
          startKey: '1'
          endKey: '50'
        module: benchmark/fabcar/initCarLedger.js
    - label: Random Transactions.
      txDuration: 10
      rateControl:
        type: fixed-rate
        opts:
          tps: 10
      workload:
        arguments:
          assets: 25
          startKey: '1'
          endKey: '50'
        module: benchmark/fabcar/randomTx.js
