---
name: Fabric
version: "1.0"
mutual-tls: false

caliper:
  blockchain: fabric

info:
  Version: "2.2.1"
  Distribution: "Kubernetes"
  Size: "Orgs: 2, Peers per org:2"
  StateDB: "goleveldb"
  Orderer: "Orgs: 1, Orderers: 3"
  OrdererConsensus: "etcdraft"
  OrdererAddress: "orderer0.orgorderer1| orderer1.orgorderer1| orderer2.orgorderer1"
  LedgerBatchTimeout: "2s"
  LedgerBatchSize: "MaxMessageCount:100 | AbsoluteMaxBytes:2 MB | PreferredMaxBytes:2 MB"
  details: "Fabric version 2.2.1 on Kubernetes. Each Organisation is mapped to a Kubernetes namespace."

clients:
  admin.Org1:
    client:
      organization: Org1
      credentialStore:
        path: /tmp/1621328523-cred/org1
        cryptoStore:
          path: /tmp/1621328523-crypto/org1
      clientPrivateKey:
        path: /home/ubuntu/HyperLedgerLab/inventory/blockchain/fabric-config/crypto-config/peerOrganizations/org1/users/User1@org1/msp/keystore/priv_sk
      clientSignedCert:
        path: /home/ubuntu/HyperLedgerLab/inventory/blockchain/fabric-config/crypto-config/peerOrganizations/org1/users/User1@org1/msp/signcerts/User1@org1-cert.pem
  admin.Org2:
    client:
      organization: Org2
      credentialStore:
        path: /tmp/1621328523-cred/org2
        cryptoStore:
          path: /tmp/1621328523-crypto/org2
      clientPrivateKey:
        path: /home/ubuntu/HyperLedgerLab/inventory/blockchain/fabric-config/crypto-config/peerOrganizations/org2/users/User1@org2/msp/keystore/priv_sk
      clientSignedCert:
        path: /home/ubuntu/HyperLedgerLab/inventory/blockchain/fabric-config/crypto-config/peerOrganizations/org2/users/User1@org2/msp/signcerts/User1@org2-cert.pem

channels:
  mychannel:
    configBinary: /home/ubuntu/HyperLedgerLab/inventory/blockchain/fabric-config/channel-artifacts/mychannel.tx
    created: False
    orderers:
    - orderer0
    - orderer1
    - orderer2
    peers:
      peer0.org1:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer1.org1:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer0.org2:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer1.org2:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
    contracts:
    - id: fabcar
      contractID: fabcar
      version: v1
      language: node
      path: /home/ubuntu/HyperLedgerLab/inventory/blockchain/src/contract/fabcar/
      metadataPath: /home/ubuntu/HyperLedgerLab/inventory/blockchain/src/contract/fabcar/metadata
      endorsement-policy:
        identities:
          - role:
              name: member
              mspId: Org1MSP
          - role:
              name: member
              mspId: Org2MSP
        policy:
          2-of:
            - signed-by: 0
            - signed-by: 1

organizations:
  Org1:
    mspid: Org1MSP
    peers:
    - peer0.org1
    - peer1.org1
    certificateAuthorities:
    - ca.org1
    adminPrivateKey:
      path: /home/ubuntu/HyperLedgerLab/inventory/blockchain/fabric-config/crypto-config/peerOrganizations/org1/users/Admin@org1/msp/keystore/priv_sk
    signedCert:
      path: /home/ubuntu/HyperLedgerLab/inventory/blockchain/fabric-config/crypto-config/peerOrganizations/org1/users/Admin@org1/msp/signcerts/Admin@org1-cert.pem
  Org2:
    mspid: Org2MSP
    peers:
    - peer0.org2
    - peer1.org2
    certificateAuthorities:
    - ca.org2
    adminPrivateKey:
      path: /home/ubuntu/HyperLedgerLab/inventory/blockchain/fabric-config/crypto-config/peerOrganizations/org2/users/Admin@org2/msp/keystore/priv_sk
    signedCert:
      path: /home/ubuntu/HyperLedgerLab/inventory/blockchain/fabric-config/crypto-config/peerOrganizations/org2/users/Admin@org2/msp/signcerts/Admin@org2-cert.pem

orderers:
  orderer0:
    url: grpcs://orderer0.orgorderer1:32000
    grpcOptions:
      ssl-target-name-override: orderer0.orgorderer1
    tlsCACerts:
      path: /home/ubuntu/HyperLedgerLab/inventory/blockchain/fabric-config/crypto-config/ordererOrganizations/orgorderer1/orderers/orderer0.orgorderer1/msp/tlscacerts/tlsca.orgorderer1-cert.pem
  orderer1:
    url: grpcs://orderer1.orgorderer1:32001
    grpcOptions:
      ssl-target-name-override: orderer1.orgorderer1
    tlsCACerts:
      path: /home/ubuntu/HyperLedgerLab/inventory/blockchain/fabric-config/crypto-config/ordererOrganizations/orgorderer1/orderers/orderer1.orgorderer1/msp/tlscacerts/tlsca.orgorderer1-cert.pem
  orderer2:
    url: grpcs://orderer2.orgorderer1:32002
    grpcOptions:
      ssl-target-name-override: orderer2.orgorderer1
    tlsCACerts:
      path: /home/ubuntu/HyperLedgerLab/inventory/blockchain/fabric-config/crypto-config/ordererOrganizations/orgorderer1/orderers/orderer2.orgorderer1/msp/tlscacerts/tlsca.orgorderer1-cert.pem

peers:
  peer0.org1:
    url: grpcs://peer0.org1:30001
    grpcOptions:
      ssl-target-name-override: peer0.org1
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: /home/ubuntu/HyperLedgerLab/inventory/blockchain/fabric-config/crypto-config/peerOrganizations/org1/peers/peer0.org1/msp/tlscacerts/tlsca.org1-cert.pem
  peer1.org1:
    url: grpcs://peer1.org1:30004
    grpcOptions:
      ssl-target-name-override: peer1.org1
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: /home/ubuntu/HyperLedgerLab/inventory/blockchain/fabric-config/crypto-config/peerOrganizations/org1/peers/peer1.org1/msp/tlscacerts/tlsca.org1-cert.pem
  peer0.org2:
    url: grpcs://peer0.org2:30101
    grpcOptions:
      ssl-target-name-override: peer0.org2
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: /home/ubuntu/HyperLedgerLab/inventory/blockchain/fabric-config/crypto-config/peerOrganizations/org2/peers/peer0.org2/msp/tlscacerts/tlsca.org2-cert.pem
  peer1.org2:
    url: grpcs://peer1.org2:30104
    grpcOptions:
      ssl-target-name-override: peer1.org2
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: /home/ubuntu/HyperLedgerLab/inventory/blockchain/fabric-config/crypto-config/peerOrganizations/org2/peers/peer1.org2/msp/tlscacerts/tlsca.org2-cert.pem

certificateAuthorities:
  ca.org1:
    url: https://ca.org1:30000
    httpOptions:
      verify: false
    tlsCACerts:
      path: /home/ubuntu/HyperLedgerLab/inventory/blockchain/fabric-config/crypto-config/peerOrganizations/org1/tlsca/tlsca.org1-cert.pem
    registrar:
    - enrollId: admin
      enrollSecret: adminpw
  ca.org2:
    url: https://ca.org2:30100
    httpOptions:
      verify: false
    tlsCACerts:
      path: /home/ubuntu/HyperLedgerLab/inventory/blockchain/fabric-config/crypto-config/peerOrganizations/org2/tlsca/tlsca.org2-cert.pem
    registrar:
    - enrollId: admin
      enrollSecret: adminpw
