---
name: network-org2
version: "1.0.0"

client:
  organization: Org2
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org2:
    mspid: Org2MSP
    peers:
    - peer0.org2
    - peer1.org2
    certificateAuthorities:
    - ca.org2
peers:
  peer0.org2:
    url: grpcs://peer0.org2:30101
    grpcOptions:
      ssl-target-name-override: peer0.org2
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: /hyperledger/caliper/workspace/fabric-config/crypto-config/peerOrganizations/org2/peers/peer0.org2/msp/tlscacerts/tlsca.org2-cert.pem
  peer1.org2:
    url: grpcs://peer1.org2:30104
    grpcOptions:
      ssl-target-name-override: peer1.org2
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: /hyperledger/caliper/workspace/fabric-config/crypto-config/peerOrganizations/org2/peers/peer1.org2/msp/tlscacerts/tlsca.org2-cert.pem
certificateAuthorities:
  ca.org2:
    url: https://ca.org2:30100
    httpOptions:
      verify: false
    tlsCACerts:
      path: /hyperledger/caliper/workspace/fabric-config/crypto-config/peerOrganizations/org2/tlsca/tlsca.org2-cert.pem

