# Config Directories
fabric_config_dirname: fabric-configs
fabric_config_dir: "{{ inventory_dir }}/{{ fabric_config_dirname }}"
crypto_config_dirname: crypto-config
crpto_config_dir: "{{ fabric_config_dir }}/{{ crypto_config_dirname }}"
channel_artifacts_dirname: channel-artifacts
channel_artifacts_dir: "{{ fabric_config_dir }}/{{ channel_artifacts_dirname }}"

# Fabric Network Config
fabric_num_orgs: 2
fabric_peers_per_org: 2
fabric_orderer_domain: orgorderer1
#fabric_orderer_address: orderer0.orgorderer1

# Metrics framework setting
# inventory_dir is an ansible variable which stores location of hosts.ini file
metrics_network_file: "{{ inventory_dir }}"

# Channel configuration
channels:                   # List of channel objects
  - name: "mychannel"
    chaincodes:
