---
test:
  clients:
    type: local
    number: 5

  rounds:
  - label: initLedger
    txNumber:
    - 1             
    rateControl:
    - type: fixed-rate
      opts:
        tps: 1
    callback: ../inventory/blockchain/benchmark/e-voting/initLedger.js

  - label: common
    txDuration:
    - 180
    rateControl:
    - type: fixed-rate
      opts:
        tps: 200
    callback: ../inventory/blockchain/benchmark/e-voting/common.js

  - label: closeElection
    txNumber:
    - 1
    rateControl:
    - type: fixed-rate
      opts:
        tps: 1 
    callback: ../inventory/blockchain/benchmark/e-voting/closeElection.js

  - label: seeResults
    txNumber:
    - 1
    rateControl:
    - type: fixed-rate
      opts:
        tps: 1
    callback: ../inventory/blockchain/benchmark/e-voting/seeResults.js

  - label: readBlockchain
    txNumber:
    - 1
    rateControl:
    - type: fixed-rate
      opts:
        tps: 1
    callback: ../inventory/blockchain/benchmark/e-voting/doNothing.js

monitor:
  type:
  - process
  process:
  - command: node
    arguments: local-client.js
    multiOutput: avg
  interval: 1
