---
test:
  clients:
    type: local
    number: 25

  rounds:
  - label: initLedgerGen
    txNumber:
    - 100000             
    rateControl:
    - type: fixed-rate
      opts:
        tps: 100
    callback: ../inventory/blockchain/benchmark/generator/initLedger.js

  - label: commonGen
    txDuration:
    - 180
    rateControl:
    - type: fixed-rate
      opts:
        tps: 100
    callback: ../inventory/blockchain/benchmark/generator/common.js

  - label: readBlockchain
    txNumber:
    - 1
    rateControl:
    - type: fixed-rate
      opts:
        tps: 1
    callback: ../inventory/blockchain/benchmark/generator/doNothing.js

monitor:
  type:
  - process
  process:
  - command: node
    arguments: local-client.js
    multiOutput: avg
  interval: 1
