# Ansible Playbook to delete Openstack Instances of Kubernetes cluster
# Note: Call with -i inventory/infra/hosts.ini
---
- hosts: localhost
  vars_prompt:
    - name: "prompt_del_inf"
      prompt: "Caution: This will delete the complete cluster including all cloud instances. Are you sure (yes/no)?"
      default: "yes"
      private: no
  tasks:
    - set_fact:
        prompt_delete_infra: "{{ prompt_del_inf }}"

# Prepare CLI node: Un-mount NFS
- hosts: os-infra
  become: true
  tasks:
    - name: Creates directory
      file:
        path: /etc/resolvconf/resolv.conf.d
        state: directory

    - name: Prepare CLI for infra delete
      block:
        - name: Unmount /opt/share in CLI
          mount:
            path: /opt/share
            fstype: nfs4
            state: "absent"

        - name: Delete DNS name from CLI
          copy:
            dest: "/etc/resolvconf/resolv.conf.d/head"
            content: |
              # Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
              #     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

        - name: Restart networking in CLI
          service:
            name: >-
               {% if ansible_os_family == "RedHat" -%}
               network
               {%- elif ansible_distribution == "Ubuntu" and ansible_distribution_release == "focal" -%}
               systemd-networkd
               {%- elif ansible_os_family == "Debian" -%}
               networking
               {%- endif %}
            state: restarted

      when: prompt_delete_infra|bool

# Delete Instances
- hosts: os-infra
  roles:
    - { "role": os_instance, "delete": true, when: prompt_delete_infra|bool }
