---
- name: restart networking
  service:
    name: >-
       {% if ansible_os_family == "RedHat" -%}
       network
       {%- elif ansible_distribution == "Ubuntu" and ansible_distribution_release == "focal" -%}
       systemd-networkd
       {%- elif ansible_os_family == "Debian" -%}
       networking
       {%- endif %}
    state: restarted

